Dictionary comprehension

In [ ]:
# creating a DIC with number as key and their squares as value using dictionary comprehension
square_dict = {x : x ** 2 for x in range (1,6)}
print(square_dict)

square_dict ={}
for x in range(1,6):
    square_dict[x] = x**2

print(square_dict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [7]:
# using dictionary comprehension to create a DIC mapping words to their lengths
words = ['apple', 'banana', 'orange']
word_lengths  ={word :len(word) for word in words if len(word) == 6}
print(word_lengths)


# in simple syntax using a normal for loop and if condition
words = ['apple', 'banana', 'orange']
word_lengths = {}

for word in words:
    if len(word) == 6:
        word_lengths[word] = len(word)

print(word_lengths)


words = [ 'apple' , ' banana ' , 'orange']
words_length = {}
for word in words:
	if len(word) == 6:
		words_length[word] = len(word)
print(words_length)


{'banana': 6, 'orange': 6}
{'banana': 6, 'orange': 6}
{'orange': 6}


Using a DIC comprehension to create a DIC from two lists

In [ ]:

keys = ['name', 'age', 'city']
values = ['Alice', 25, 'new york']

dic = {}
for i in range(len(keys)):
    dic[keys[i]] = values[i]

print(dic)

# creating a dic where elements from the 'keys' list are keys
# and elements from the 'values' list and using dic comprehension

keys = ['name', 'age', 'city']
values = ['Alice', 25, 'new york']

# Dictionary comprehension with zip()
dic = {k: v for k, v in zip(keys, values)}

print(dic)




{'name': 'Alice', 'age': 25, 'city': 'new york'}
{'name': 'Alice', 'age': 25, 'city': 'new york'}


**CREATING NUMPY ARRAY**

In [29]:
import numpy as np 

# creating a numpy array filled with ones
ones_arr = np.ones((2,2))
# convert numpy array to pandas DataFrame
print(ones_arr)
ones_arr[1][1]

[[1. 1.]
 [1. 1.]]


np.float64(1.0)

np.arange()

In [31]:
import numpy as np
# create array using arange
arr = np.arange(0,11,2)
print("Array from arange:")
print(arr)

Array from arange:
[ 0  2  4  6  8 10]


np.linspace()

In [40]:
import numpy as np
#create array using linspace
lin_arr = np.linspace(0,10,10)
# print the array
print("Array from linspace:")
print(lin_arr)

lin_arr = np.linspace(0,10,11)
# print the array
print("Array from linspace:")
print(lin_arr)

Array from linspace:
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
Array from linspace:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [7]:
import numpy as np
random = np.random.rand (3,3)

print(random)

print(np.random.rand(3,3) * 500)

rand_arr = 40 + np.random.rand(3,3)*500

print(rand_arr)

[[0.41986757 0.29822899 0.88891575]
 [0.13364122 0.5226456  0.82049329]
 [0.04458024 0.55654308 0.17486543]]
[[389.69232327  70.71110994  62.19848826]
 [ 59.91275153 427.93340541 466.30340867]
 [168.45174219 173.35299162 486.2749851 ]]
[[103.01607965  89.44215992 275.27221564]
 [126.53350863 174.09427018  47.1740592 ]
 [300.8333728  434.14863078 156.49666313]]


In [8]:
import numpy as np

# create a 2-dimensional array with specified dimension
arr = np.array([1,2,3,4], ndmin=2)

print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3 4]]
(1, 4)
2


In [ ]:
import numpy as np
# crete a 2-dimensional array with specified dimension
arr = np.array([1,2,3,4], ndmin=2)

reshaped_arr = arr.reshape((4,1))

print(reshaped_arr)
print(reshaped_arr)

[[1]
 [2]
 [3]
 [4]]
[3]


In [15]:
import numpy as np
str_arr = np.array(['ABC','SDF','DSSF',89], dtype=np.str_)

print("string array:", str_arr)
print(type(str_arr))
print(list(str_arr))
print(type(list(str_arr)))

string array: ['ABC' 'SDF' 'DSSF' '89']
<class 'numpy.ndarray'>
[np.str_('ABC'), np.str_('SDF'), np.str_('DSSF'), np.str_('89')]
<class 'list'>


In [16]:
import numpy as np
int_arr = np.array([1,2,3,4,8.0],dtype=np.int64, ndmin=2)

print("interger array:", int_arr)

interger array: [[1 2 3 4 8]]


In [17]:
import numpy as np
bool_arr = np.array ([True, False, True, 7], dtype=np.bool)
print('bool array: ', bool_arr)

bool array:  [ True False  True  True]


In [25]:
string = "jan= january ; feb =febuary ; mar = march"

# Step 1: Split into parts by semicolon
string_parts = string.split(';')

# Step 2: Create empty dictionary
dictionary = {}

# Step 3: Loop through parts and split by '='
for substring in string_parts:
    key, value = substring.split('=')
    dictionary[key.strip()] = value.strip()  # remove spaces

print(dictionary)


{'jan': 'january', 'feb': 'febuary', 'mar': 'march'}


Indexing and slicing numpy arrays

In [31]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]], ndmin=2)
print(arr.ndim)
print(arr[1][2])
print(arr[1,2])
print(arr[1:3])
print(arr[1:3,:])
print(arr[2][1:])
print(arr[2,1:])

2
6
6
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[8 9]
[8 9]


In [32]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]], ndmin=2)

mask = arr > 5
print("boolean mask for values greater than 5:\n", mask)
filtered = arr[mask]
print("values greater than 5:\n", filtered)

boolean mask for values greater than 5:
 [[False False False]
 [False False  True]
 [ True  True  True]]
values greater than 5:
 [6 7 8 9]


In [36]:
import numpy as np
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

b = arr[:2 , 1:3]
print(b)
b[0,1] = 77
print(arr)

[[2 3]
 [6 7]]
[[ 1  2 77  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

mean_arr1 = np.mean(arr1)
std_dev_arr2 = np.std(arr2)

print("mean of arr1:", mean_arr1)
print("standard deviation of arr2:", std_dev_arr2)

mean of arr1: 2.0
standard deviation of arr2: 0.816496580927726


In [ ]:
list1 = [1,2,3,4,5]
k =  2
[4,5,1,2,3]

In [43]:
list1 = [1, 2, 3, 4, 5]
k = 2

rotated = list1[-k:] + list1[:-k]
print(rotated)


[4, 5, 1, 2, 3]
